### ISSUE TITLE
Question about How to mapping varibales between fully-stripped binary and typing-stripped binary?

### ISSUE THREAD

**Issue by Ch3nYe** [sefcom/VarBERT#2]
Great work! 👏

I am confused about how to correspond the variables in the fully-stripped binary to the variables in the typing-stripped binary, it also involves distinguishing variables in the fully-stripped binaries that are human-written from those that are decompiler-generated. 

Looking forward to your reply.

**Comment by Atipriya** [comment]
Hello @Ch3nYe

Thank you for your interest in our work.

We use [Joern ](https://github.com/joernio/joern) to parse the decompiled code for both type-stripped and stripped binaries and collect variables for each decompiled function. Based on the order of variables returned by Joern, we map these variables. We have several checks to map variables correctly. After mapping, we update the stripped decompiled function with unique identifiers and mapped variable names. 


Here is our variable mapping code: https://github.com/sefcom/VarBERT/blob/main/varcorpus/dataset-gen/variable_matching.py

The version of Joern we used to generate VarCorpus: https://www.dropbox.com/scl/fi/toh6087y5t5xyln47i5ih/modified_joern.tar.gz?rlkey=lfvjn1u7zvtp9a4cu8z8vgsof&dl=0

To determine if a variable is developer-assigned, we rely on DWARF Debug information. We use [pyelftools ](https://github.com/eliben/pyelftools) to read the debug information and collect all the variable names. Using this information, we label variables in our variable mapping script. Variables present in debug information are labeled as developer-assigned, while the remaining are labeled as decompiler-generated.

Here is our code for reading DWARF information: https://github.com/sefcom/VarBERT/blob/main/varcorpus/dataset-gen/dwarf_info.py

Happy to answer any further questions.

**Comment by Ch3nYe** [comment]
Great!

Thanks for your answer.
